export * from "./InstagramIcon";
export * from "./LinkedlnIcon";
export * from "./WordpressIcon";
export * from "./CancelIcon";
export * from "./AddIcon";
export * from "./RecoverIcon";
export * from "./DeleteIcon";
export * from "./LaunchIcon";
export * from "./PencilIcon";
